# Build file for being executed using a trigger based on repo commit (using $SHORT_SHA)

timeout: '120s'

options:
  env:
    - CLOUDSDK_RUN_REGION=europe-west1
    - CLOUDSDK_RUN_PLATFORM=managed

substitutions:
  _IMAGE_NAME: cloudrun_managed_demo
  _SERVICE_NAME: managed-demo
  
steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:$SHORT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args: ['push', 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:$SHORT_SHA']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: Deploy
    args:
        - run
        - deploy
        - $_SERVICE_NAME
        - --image 
        - gcr.io/$PROJECT_ID/$_IMAGE_NAME:$SHORT_SHA
        - --allow-unauthenticated