# Build file for being executed using a trigger based on repo commit (using $SHORT_SHA)

timeout: '120s'

options:
  env:
    - 'CLOUDSDK_RUN_PLATFORM=gke'
    - 'CLOUDSDK_RUN_CLUSTER=ci-cd-demo'
    - 'CLOUDSDK_RUN_CLUSTER_LOCATION=europe-west1-c'
substitutions:
  _IMAGE_NAME: cloudrun_anthos_demo
  _SERVICE_NAME: anthos-demo

steps:
- name: mirror.gcr.io/library/golang
  id: Test
  args: ["go", "test","./..."]
  env: ['GO111MODULE=on']
    
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
  - build
  - -t
  - gcr.io/$PROJECT_ID/$_IMAGE_NAME:$SHORT_SHA
  - .

- name: gcr.io/cloud-builders/docker
  id: Push
  args: 
  - push
  - gcr.io/$PROJECT_ID/$_IMAGE_NAME:$SHORT_SHA

- name: gcr.io/cloud-builders/gcloud
  id: Deploy
  args:
    - run
    - deploy
    - $_SERVICE_NAME
    - --image 
    - gcr.io/$PROJECT_ID/$_IMAGE_NAME:$SHORT_SHA
    - --connectivity
    - external
