# Build file for being executed using a trigger based on repo commit (using $SHORT_SHA)
# It uses the open source Kritis signer (https://github.com/grafeas/kritis)
timeout: '300s'

options:
  env:
  - 'CLOUDSDK_RUN_PLATFORM=gke'
  - 'CLOUDSDK_RUN_CLUSTER=ci-cd-demo'
  - 'CLOUDSDK_RUN_CLUSTER_LOCATION=europe-west1-c'

substitutions:
  _IMAGE_NAME: cloudrun_anthos_demo
  _SERVICE_NAME: anthos-demo
  _VULNZ_NOTE: vulnz-note
  _KMS_LOCATION: europe-west1
  _KMS_KEYRING: binauthz
  _VULNZ_KMS_KEY: vulnz-signer
  _VULNZ_KMS_KEY_VERSION: "1"
  _VULNZ_KMS_DIGEST_ALG: SHA512
  _KRITIS_POLICY: kritis-policies/policy-low.yaml

steps:
- name: mirror.gcr.io/library/golang
  id: Test
  args: ["go", "test","./..."]
  env: ['GO111MODULE=on']
    
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
  - build
  - -t
  - gcr.io/$PROJECT_ID/$_IMAGE_NAME:$SHORT_SHA
  - .

# Using an alternative "docker push" step in order to pass the full image digest to the next steps
# The Kritis container has no docker, nor gcloud to get the full digest by itself
- name: gcr.io/cloud-builders/docker
  id: Push
  entrypoint: /bin/bash
  args:
  - -c
  - |
    docker push gcr.io/$PROJECT_ID/$_IMAGE_NAME:$SHORT_SHA &&
    docker image inspect gcr.io/$PROJECT_ID/$_IMAGE_NAME:$SHORT_SHA --format '{{index .RepoDigests 0}}' > image-digest.txt &&
    cat image-digest.txt

- name: gcr.io/$PROJECT_ID/kritis-signer
  id: Sign
  entrypoint: /bin/bash
  args:
  - -c
  - |-
    FQ_KMS_KEY="projects/${PROJECT_ID}/\
    locations/${_KMS_LOCATION}/\
    keyRings/${_KMS_KEYRING}/\
    cryptoKeys/${_VULNZ_KMS_KEY}/\
    cryptoKeyVersions/${_VULNZ_KMS_KEY_VERSION}"

    /kritis/signer \
    -v=10 \
    -alsologtostderr \
    -image=$(/bin/cat image-digest.txt) \
    -policy=${_KRITIS_POLICY} \
    -kms_key_name="$${FQ_KMS_KEY}" \
    -kms_digest_alg=${_VULNZ_KMS_DIGEST_ALG} \
    -note_name="projects/${PROJECT_ID}/notes/${_VULNZ_NOTE}"
    
- name: gcr.io/cloud-builders/gcloud
  id: Deploy
  args:
    - run
    - deploy
    - $_SERVICE_NAME
    - --image 
    - gcr.io/$PROJECT_ID/$_IMAGE_NAME:$SHORT_SHA
    - --connectivity
    - external
